openapi: 3.0.1
info:
  title: API Claim Home
  description: Business API containing claim/assistance opening and management operations for Spain.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: "1.0"
servers:
  - description: Preproduction (PRE) (Internal consumers).
    url: https://apisb.mapfre.net/esp/srv/api/home/1.0
  - description: Preproduction (PRE) (External consumers).
    url: https://apisb.mapfre.com/esp/srv/api/home/1.0
security:
  - mapfre_auth:
      - esp:home/claim:create
      - esp:home/claim:read
      - esp:home/claim:update
      - esp:home/assistance:create
      - esp:home/assistance:read
tags:
  - name: Claim
    description: Existing operations inside insurance claims.
  - name: Proceeding
    description: Existing operations to treat the set of data that encompasses the characteristics of a claim or assistance.
  - name: Communication
    description: Set of operations for consulting communications within a claim or assistance.
  - name: Indemnity
    description: Set of operations for consulting insurance indemnities.
  - name: Document
    description: Set of operations for document management.
  - name: Task
    description: Set of operations for consulting tasks of a claim or assistance.
  - name: Assistance
    description: Existing operations inside assistances.
paths:
  /claim/client:
    get:
      tags:
        - Claim
      summary: Get client data associated with a policy.
      description: Get the client's policy details, according to the variables provided to perform the search.
      operationId: getClaimClient
      security:
        - mapfre_auth:
            - esp:home/claim:read
  /claim:
    post:
      tags:
        - Claim
      summary: Generate claim.
      description: Generate claim.
      operationId: generateClaimPatrimonial
      security:
        - mapfre_auth:
            - esp:home/claim:create
  /claims/searchClaims:
    post:
      tags:
        - Claim
      summary: Finds one or more existing claims.
      description: Finds one or more existing claims, according to the variables provided to perform the search.
      operationId: getClaims
      security:
        - mapfre_auth:
            - esp:home/claim:read
  /claim/{claimId}:
    get:
      tags:
        - Claim
      summary: Get a certain claim.
      description: Get a certain claim, given its unique claim ID.
      operationId: getClaimHome
      security:
        - mapfre_auth:
            - esp:home/claim:read
  /claims/getClaims:
    get:
      tags:
        - Claim
      summary: Get claims for a policy.
      description: Get claims according to the parameters provided.
      operationId: getCheckClaims
      security:
        - mapfre_auth:
            - esp:home/claim:read
  /claim/interventions:
    post:
      tags:
        - Claim
      summary: Get interventions for claim.
      description: Get interventions for claim.
      operationId: getClaimInterventions
      security:
        - mapfre_auth:
            - esp:home/claim:read
  /claim/proceedings/searchProceedings:
    post:
      tags:
        - Proceeding
      summary: Finds one or more existing proceedings.
      description: Finds one or more existing proceedings, according to the variables provided to perform the search.
      operationId: getProceedings
      security:
        - mapfre_auth:
            - esp:home/claim:read
  /claim/proceeding/{proceedingId}:
    get:
      tags:
        - Proceeding
      summary: Get a certain proceeding.
      description: Get a certain proceeding, given its unique proceeding ID.
      operationId: getProceeding
      security:
        - mapfre_auth:
            - esp:home/claim:read
  /claim/proceeding/{proceedingId}/communications:
    get:
      tags:
        - Communication
      summary: Finds one or more existing communications for a certain proceeding.
      description: Finds one or more existing communications, according to the variables provided to perform the search.
      operationId: getProceedingCommunications
      security:
        - mapfre_auth:
            - esp:home/claim:read
  /claim/proceeding/{proceedingId}/communication/{communicationId}:
    get:
      tags:
        - Communication
      summary: Gets communication detail for a certain id and type.
      description: Gets communication detail for a certain id and type.
      operationId: getProceedingCommunication
      security:
        - mapfre_auth:
            - esp:home/claim:read
  /claim/proceeding/{proceedingId}/indemnities:
    get:
      tags:
        - Indemnity
      summary: Get the indemnities from a certain proceeding.
      description: Get the indemnities from a certain proceeding, given its unique proceeding ID.
      operationId: getProceedingIndemnity
      security:
        - mapfre_auth:
            - esp:home/claim:read
  /claim/proceeding/{proceedingId}/message:
    post:
      tags:
        - Proceeding
      summary: Generate a message for a certain proceeding.
      description: Generate a message for a certain proceeding.
      operationId: generateProceedingMessage
      security:
        - mapfre_auth:
            - esp:home/claim:create
  /claim/proceeding/{proceedingId}/tasks:
    get:
      tags:
        - Task
      summary: Get a certain proceeding tasks.
      description: Get tasks from a certain proceeding.
      operationId: getProceedingTasks
      security:
        - mapfre_auth:
            - esp:home/claim:read
  /claim/proceeding/{proceedingId}/task/{taskId}:
    get:
      tags:
        - Task
      summary: Finds an associated task for a certain proceeding.
      description: Finds an associated task according to the variables provided to perform the search.
      operationId: getProceedingTask
      security:
        - mapfre_auth:
            - esp:home/claim:read
  /claim/proceeding/{proceedingId}/task/{taskId}/documents:
    get:
      tags:
        - Document
      summary: Get task's documents.
      description: Get task's documents.
      operationId: getProceedingTaskDocuments
      security:
        - mapfre_auth:
            - esp:home/claim:read
  /claim/proceeding/{proceedingId}/task/{taskId}/document:
    post:
      tags:
        - Document
      summary: Create task document.
      description: Create task document.
      operationId: postProceedingTaskDocument
      security:
        - mapfre_auth:
            - esp:home/claim:read
  /claim/proceeding/{proceedingId}/documents:
    get:
      tags:
        - Document
      summary: Get proceeding's documents.
      description: Get proceeding's documents.
      operationId: getProceedingDocuments
      security:
        - mapfre_auth:
            - esp:home/claim:read
  /claim/proceeding/{proceedingId}/document:
    post:
      tags:
        - Document
      summary: Create proceeding documents.
      description: Create proceeding documents.
      operationId: postProceedingDocument
      security:
        - mapfre_auth:
            - esp:home/claim:read
  /claim/proceeding/{proceedingId}/document/{documentId}:
    get:
      tags:
        - Document
      summary: Get proceeding document.
      description: Get proceeding document.
      operationId: getProceedingDocument
      security:
        - mapfre_auth:
            - esp:home/claim:read
    put:
      tags:
        - Document
      summary: Update document metadata.
      description: Update document metadata.
      operationId: putProceedingDocument
      security:
        - mapfre_auth:
            - esp:home/claim:update
  /claim/assistance/client:
    get:
      tags:
        - Assistance
      summary: Get client data associated with a policy or contract.
      description: Get the client's policy details or contract details, according to the variables provided to perform the search.
      operationId: getAssistanceClient
      security:
        - mapfre_auth:
            - esp:home/assistance:read
  /claim/assistance:
    post:
      tags:
        - Assistance
      summary: Generate assistance.
      description: Generate assistance.
      operationId: generateAssistance
      security:
        - mapfre_auth:
            - esp:home/assistance:create
  /claim/assistance/jobs:
    get:
      tags:
        - Assistance
      summary: Get a list of assistance jobs.
      description: Get a list of assistance jobs.
      operationId: getAssistanceJobs
      security:
        - mapfre_auth:
            - esp:home/assistance:read
  /claim/assistances/searchAssistances:
    post:
      tags:
        - Assistance
      summary: Finds one or more existing assistances.
      description: Finds one or more existing assistances, according to the variables provided to perform the search.
      operationId: getAssistances
      security:
        - mapfre_auth:
            - esp:home/assistance:read
  /claim/assistance/{assistanceId}:
    get:
      tags:
        - Assistance
      summary: Get detailed information for a certain assistance.
      description: Get a certain assistance, given its unique assistance ID.
      operationId: getAssistanceDetail
      security:
        - mapfre_auth:
            - esp:home/assistance:read
  /claim/assistance/proceedings/searchProceedings:
    post:
      tags:
        - Proceeding
      summary: Finds one or more existing assistance proceedings.
      description: >-
        Finds one or more existing assistance proceedings, according to the variables
        provided to perform the search.
      operationId: getAssistanceProceedings
      security:
        - mapfre_auth:
            - esp:home/assistance:read
  /claim/assistance/proceeding/{proceedingId}:
    get:
      tags:
        - Proceeding
      summary: Gets assistance proceeding detailed info.
      description: Gets assistance proceeding detailed info.
      operationId: getAssisProceedDetail
      security:
        - mapfre_auth:
            - esp:home/assistance:read
  /claim/assistance/proceeding/{proceedingId}/tasks:
    get:
      tags:
        - Task
      summary: Get a certain assistance proceeding tasks.
      description: Get tasks from a certain assistance proceeding.
      operationId: getAssisProceedTasks
      security:
        - mapfre_auth:
            - esp:home/assistance:read
  /claim/assistance/proceeding/{proceedingId}/task/{taskId}:
    get:
      tags:
        - Task
      summary: Finds an associated task for a certain assistance proceeding.
      description: Finds an associated task according to the variables provided to perform the search.
      operationId: getAssisProceedTask
      security:
        - mapfre_auth:
            - esp:home/assistance:read
  /claim/assistance/proceeding/{proceedingId}/communications:
    get:
      tags:
        - Communication
      summary: Finds one or more existing communications for a certain assistance proceeding.
      description: Finds one or more existing communications, according to the variables provided to perform the search.
      operationId: getAssisProceedComs
      security:
        - mapfre_auth:
            - esp:home/assistance:read
  /claim/assistance/proceeding/{proceedingId}/communication/{communicationId}:
    get:
      tags:
        - Communication
      summary: Gets communication detail for a certain id and type.
      description: Gets communication detail for a certain id and type.
      operationId: getAssisProceedCom
      security:
        - mapfre_auth:
            - esp:home/assistance:read
  /claim/assistance/proceeding/{proceedingId}/message:
    post:
      tags:
        - Proceeding
      summary: Generate a message for a certain assistance proceeding.
      description: Generate a message for a certain assistance proceeding.
      operationId: generateAssisProceedMsg
      security:
        - mapfre_auth:
            - esp:home/assistance:create
components:
  securitySchemes:
    mapfre_auth:
      type: oauth2
      description: This API uses OAuth2.0 with Resource Owner Password credentials flow (a.k.a. password).
      flows:
        password:
          tokenUrl: https://apisb.mapfre.com/auth/oauth/v2/token
          scopes:
            esp:home/claim:create: Grants access to create a claim.
            esp:home/claim:read: Grants access to search for existing claims.
            esp:home/claim:update: Grants access to edit existing claims.
            esp:home/assistance:create: Grants access to create a assistance.
            esp:home/assistance:read: Grants access to search for existing assistances.
